# Build stage
FROM node:18-alpine AS builder

WORKDIR /app

# Copy package files
COPY manager/frontend/package*.json ./
RUN npm ci

# Copy source code
COPY manager/frontend/ .

# Build application
RUN npm run build

RUN ls -a 

# Runtime stage
FROM nginx:alpine

# Copy build results
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy diagnose.js file
COPY manager/frontend/diagnose.js /usr/share/nginx/html/

# Copy nginx configuration
COPY manager/frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
